name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java-version: [ 11 ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build
        env:
          ORG_GRADLE_PROJECT_githubPackageUsername: ${{ github.actor }}
          ORG_GRADLE_PROJECT_githubPackagePassword: ${{ secrets.GITHUB_TOKEN }}
